### ISSUE TITLE
what version of qtile do you have?

### ISSUE THREAD

**Issue by zackfall** [m-col/qtile-config#2]
I'm sorry if is something stupid to ask, but i tried to do something like you did in the wayland file, but when i tried to import the InputConfig class, I get an import error bc the class doesn't exists

**Comment by m-col** [comment]
Ah yes sorry about that. `InputConfig` comes from this PR: https://github.com/qtile/qtile/pull/2548. I'm running from the git version, but also sometimes have a PR on top. If you decide to also run that PR, any feedback on it would be appreciated!

**Comment by zackfall** [comment]
Ooh, thanks, i will try it, looks like a very cool feature
